//! The print half of the info model: [`InfoValue`] (per-field human render)
//! and [`InfoView`] (a whole type's section tree). A view struct that derives
//! both `serde::Serialize` and [`InfoView`](macro@crate::InfoView) drives the
//! two info outputs — machine JSON and themed terminal text — from one place.
//!
//! - [`InfoValue::render_value`] returns a *painted* SGR string for one field,
//!   matching [`push_field`](super::push_field)'s `(label, colored_value)`
//!   contract. The semantic [`Value`](super::Value) enum impls it (size /
//!   count / timestamp gradients live in `render/`); the std blanket impls
//!   below cover plain fields; per-type enums whose print label diverges from
//!   their JSON token impl it themselves (orphan-legal: local type, this
//!   trait).
//! - [`InfoView`] is what `#[derive(InfoView)]` generates: `info_nodes()`
//!   walks the fields in declaration order, producing a tree of [`InfoNode`]s
//!   — scalar fields become [`InfoNode::Row`]s, `#[info(nest)]` fields splice
//!   in a sub-view's nodes (a *titled* sub-view becomes a nested
//!   [`InfoNode::Block`]; an untitled one inlines its rows). Display blocks
//!   and JSON sub-objects are the same structural fact, so the two outputs
//!   stay in step from one definition.
//! - [`render_info`] walks that tree into themed terminal lines, the shared
//!   driver that replaces every hand-written `render_section`.

use std::borrow::Cow;

use peek_io::sanitize_terminal_controls;
use peek_theme::PeekTheme;

use super::{push_field, push_section_header};

/// Render one info-field value to a themed (SGR-painted) string.
///
/// The blanket impls here cover plain field types; [`Value`](super::Value)
/// carries the semantic kinds with bespoke colouring; per-type enums whose
/// human label differs from their serde token impl this directly.
pub trait InfoValue {
    /// Themed value string for the field's `(label, value)` row.
    fn render_value(&self, theme: &PeekTheme) -> String;
}

/// One node of an info view: either a labelled value row or a titled block
/// holding further nodes. The tree mirrors the JSON structure — a [`Block`]
/// is a nested object, a [`Row`] a leaf.
///
/// [`Block`]: InfoNode::Block
/// [`Row`]: InfoNode::Row
#[derive(Clone)]
pub enum InfoNode {
    /// A `Label  value` line. The label is usually a `&'static str` literal
    /// (`"Lines"`), but `Cow` lets a hand-built view supply an owned, dynamic
    /// label (e.g. a CSV column's `" 1: header"`).
    Row {
        label: Cow<'static, str>,
        value: String,
    },
    /// A `── Title ──` section header followed by its body nodes.
    Block { title: String, body: Vec<InfoNode> },
    /// A pre-rendered line, emitted verbatim — for content that doesn't fit
    /// the `label  value` grid (e.g. a CSS colour-swatch row). Hand-built
    /// views only; the derive never produces one.
    Line(String),
}

impl InfoNode {
    /// Whether this node produces any visible output. A [`Block`](InfoNode::Block)
    /// with no rendering descendants is empty and is skipped entirely (header
    /// included) — the all-optional-absent section vanishes.
    fn renders(&self) -> bool {
        match self {
            InfoNode::Row { .. } | InfoNode::Line(_) => true,
            InfoNode::Block { body, .. } => body.iter().any(InfoNode::renders),
        }
    }
}

/// A type's whole info view: the ordered section/row tree. Generated by
/// `#[derive(InfoView)]`; consumed by [`render_info`] (print) while
/// `serde::Serialize` drives the parallel JSON.
pub trait InfoView {
    /// The view's nodes, in declaration order, skips already applied.
    fn info_nodes(&self, theme: &PeekTheme) -> Vec<InfoNode>;
}

/// A `None` sub-view contributes nothing; `Some` splices its nodes. Lets a
/// `#[info(nest)]` field be `Option<T>` (absent → no block / no rows) without
/// a separate skip attribute.
impl<T: InfoView> InfoView for Option<T> {
    fn info_nodes(&self, theme: &PeekTheme) -> Vec<InfoNode> {
        match self {
            Some(v) => v.info_nodes(theme),
            None => Vec::new(),
        }
    }
}

/// Walk a view's node tree into themed terminal lines — the shared driver
/// that replaces every hand-written `render_section`.
pub fn render_info(lines: &mut Vec<String>, view: &impl InfoView, theme: &PeekTheme) {
    for node in view.info_nodes(theme) {
        render_node(lines, &node, theme);
    }
}

fn render_node(lines: &mut Vec<String>, node: &InfoNode, theme: &PeekTheme) {
    match node {
        InfoNode::Row { label, value } => push_field(lines, label, value, theme),
        InfoNode::Line(line) => lines.push(line.clone()),
        InfoNode::Block { title, body } => {
            if !body.iter().any(InfoNode::renders) {
                return;
            }
            lines.push(String::new());
            push_section_header(lines, title, theme);
            for child in body {
                render_node(lines, child, theme);
            }
        }
    }
}

// --- std blanket impls -----------------------------------------------------
//
// A view struct mixing `Value` fields with plain ones just works. Strings and
// bools paint in the value color; integers reuse the count gradient (the
// common case — a bare integer field is a cardinal). `Option` renders its
// inner value (the empty case is handled by skip, not here); `Vec` joins with
// commas.

// Free-text values are often file-controlled metadata (titles, authors,
// tags, subjects), so strip terminal-control sequences before painting —
// the generic choke for every derived InfoView string field.
impl InfoValue for String {
    fn render_value(&self, theme: &PeekTheme) -> String {
        theme.paint_value(sanitize_terminal_controls(self).as_ref())
    }
}

impl InfoValue for &str {
    fn render_value(&self, theme: &PeekTheme) -> String {
        theme.paint_value(sanitize_terminal_controls(self).as_ref())
    }
}

impl InfoValue for bool {
    fn render_value(&self, theme: &PeekTheme) -> String {
        theme.paint_value(if *self { "yes" } else { "no" })
    }
}

macro_rules! impl_info_value_int {
    ($($t:ty),*) => {$(
        impl InfoValue for $t {
            fn render_value(&self, theme: &PeekTheme) -> String {
                super::paint_count(*self as usize, theme)
            }
        }
    )*};
}
impl_info_value_int!(u8, u16, u32, u64, usize, i8, i16, i32, i64, isize);

impl<T: InfoValue> InfoValue for Option<T> {
    fn render_value(&self, theme: &PeekTheme) -> String {
        match self {
            Some(v) => v.render_value(theme),
            None => String::new(),
        }
    }
}

impl<T: InfoValue> InfoValue for Vec<T> {
    fn render_value(&self, theme: &PeekTheme) -> String {
        self.iter()
            .map(|v| v.render_value(theme))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

/// Zero-test backing the derive's print-only `#[info(skip_if_zero)]`. Lets a
/// numeric field — whether a plain integer or a [`Value`](super::Value) of a
/// numeric kind — be hidden from the printed section while JSON still emits
/// its `0`. Non-numeric values are never "zero".
pub trait MaybeZero {
    fn is_zero_value(&self) -> bool;
}

macro_rules! impl_maybe_zero_int {
    ($($t:ty),*) => {$(
        impl MaybeZero for $t {
            fn is_zero_value(&self) -> bool { *self == 0 }
        }
    )*};
}
impl_maybe_zero_int!(u8, u16, u32, u64, usize, i8, i16, i32, i64, isize);

impl MaybeZero for super::Value {
    fn is_zero_value(&self) -> bool {
        use super::Value;
        match self {
            Value::Size(n) | Value::Count(n) | Value::DurationMs(n) => *n == 0,
            Value::Int(n) => *n == 0,
            Value::Ratio(r) => *r == 0.0,
            // A Split's value *is* its JSON payload, so `skip_if_zero` reads it
            // directly: a numeric-zero payload hides the print row while JSON
            // still carries the 0. Non-numeric payloads are never "zero".
            Value::Split { json, .. } => json.as_f64() == Some(0.0),
            _ => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use peek_theme::{PeekTheme, PeekThemeName, StyleMode, load_embedded_theme};

    use super::*;
    use crate::info::{Role, Value};

    fn plain_theme() -> PeekTheme {
        let mut t = PeekTheme::from_syntect(&load_embedded_theme(
            PeekThemeName::default().tmtheme_source(),
        ));
        // Plain so asserts can match raw substrings without SGR escapes.
        t.style_mode = StyleMode::Plain;
        t
    }

    /// A throwaway [`InfoView`] wrapping a fixed node list, so the walker can
    /// be driven through its real public entry point.
    struct Nodes(Vec<InfoNode>);
    impl InfoView for Nodes {
        fn info_nodes(&self, _theme: &PeekTheme) -> Vec<InfoNode> {
            self.0.clone()
        }
    }

    fn render(nodes: Vec<InfoNode>) -> Vec<String> {
        let mut lines = Vec::new();
        render_info(&mut lines, &Nodes(nodes), &plain_theme());
        lines
    }

    fn row(label: &str, value: &str) -> InfoNode {
        InfoNode::Row {
            label: label.to_string().into(),
            value: value.to_string(),
        }
    }
    fn block(title: &str, body: Vec<InfoNode>) -> InfoNode {
        InfoNode::Block {
            title: title.to_string(),
            body,
        }
    }

    #[test]
    fn renders_predicate() {
        assert!(row("a", "b").renders());
        assert!(InfoNode::Line("x".into()).renders());
        // An empty block, and a block whose only child is an empty block, are
        // both invisible — the all-optional-absent section vanishes.
        assert!(!block("T", vec![]).renders());
        assert!(!block("Outer", vec![block("Inner", vec![])]).renders());
        // A single rendering descendant at any depth keeps the block alive.
        assert!(block("T", vec![row("a", "b")]).renders());
        assert!(
            block(
                "Outer",
                vec![block("Inner", vec![InfoNode::Line("x".into())])]
            )
            .renders()
        );
    }

    #[test]
    fn empty_block_emits_nothing() {
        // No header, no leading blank line — the block disappears entirely.
        assert!(
            render(vec![block("Stats", vec![])]).is_empty(),
            "all-skipped block must vanish"
        );
    }

    #[test]
    fn nested_all_empty_block_vanishes() {
        let out = render(vec![block("Outer", vec![block("Inner", vec![])])]);
        assert!(
            out.is_empty(),
            "block of only-empty blocks must vanish: {out:?}"
        );
    }

    #[test]
    fn a_lone_line_keeps_its_block_alive() {
        let out = render(vec![block("Outer", vec![InfoNode::Line("hello".into())])]);
        assert!(
            out.iter().any(|l| l.contains("Outer")),
            "header present: {out:?}"
        );
        assert!(out.iter().any(|l| l.contains("hello")));
    }

    #[test]
    fn block_with_row_renders_header_blank_and_row() {
        let out = render(vec![block("Stats", vec![row("Lines", "10")])]);
        // A rendered block is preceded by a blank separator line.
        assert_eq!(out.first().map(String::as_str), Some(""));
        assert!(out.iter().any(|l| l.contains("Stats")));
        assert!(out.iter().any(|l| l.contains("Lines") && l.contains("10")));
    }

    #[test]
    fn empty_subblock_pruned_while_parent_row_stays() {
        let out = render(vec![block(
            "Outer",
            vec![block("EmptyInner", vec![]), row("Key", "val")],
        )]);
        assert!(out.iter().any(|l| l.contains("Outer")));
        assert!(
            out.iter().all(|l| !l.contains("EmptyInner")),
            "pruned subblock header leaked: {out:?}"
        );
        assert!(out.iter().any(|l| l.contains("Key") && l.contains("val")));
    }

    #[test]
    fn blanket_value_impls() {
        let t = plain_theme();
        assert_eq!(true.render_value(&t), "yes");
        assert_eq!(false.render_value(&t), "no");
        assert_eq!("x".render_value(&t), "x");
        assert_eq!(
            vec!["a".to_string(), "b".to_string()].render_value(&t),
            "a, b"
        );
        assert_eq!(Some("z".to_string()).render_value(&t), "z");
        // None renders empty — its row is meant to be skipped, not shown blank.
        assert_eq!(None::<String>.render_value(&t), "");
    }

    #[test]
    fn maybe_zero_covers_numeric_values_only() {
        assert!(0u32.is_zero_value());
        assert!(!3u32.is_zero_value());
        assert!(Value::Count(0).is_zero_value());
        assert!(!Value::Count(5).is_zero_value());
        assert!(Value::Ratio(0.0).is_zero_value());
        // A non-numeric value is never "zero", even if it stringifies to "0".
        assert!(!Value::Text("0".into()).is_zero_value());
        assert!(!Value::Bool(false).is_zero_value());
        // A Split reads its JSON payload: numeric zero is zero, anything else
        // (non-zero number, string, bool) is not.
        assert!(Value::split("0 min", Role::Value, serde_json::json!(0)).is_zero_value());
        assert!(!Value::split("5 min", Role::Value, serde_json::json!(5)).is_zero_value());
        assert!(!Value::split("x", Role::Value, serde_json::json!("x")).is_zero_value());
        assert!(!Value::split("no", Role::Value, serde_json::json!(false)).is_zero_value());
    }
}
