//! The print half of the info model: [`InfoValue`] (per-field human render)
//! and [`InfoSection`] (a whole flat section). A view struct that derives both
//! `serde::Serialize` and [`InfoSection`](macro@crate::InfoSection) drives the
//! two info outputs — machine JSON and themed terminal text — from one place.
//!
//! - [`InfoValue::render_value`] returns a *painted* SGR string for one field,
//!   matching [`push_field`](super::push_field)'s `(label, colored_value)`
//!   contract. The semantic [`Value`](super::Value) enum impls it (size /
//!   count / timestamp gradients live in `render/`); the std blanket impls
//!   below cover plain fields; per-type enums whose print label diverges from
//!   their JSON token impl it themselves (orphan-legal: local type, this
//!   trait).
//! - [`InfoSection`] is what `#[derive(InfoSection)]` generates: a `title()`
//!   plus `rows()` walking the fields in declaration order, each row's label
//!   from `#[info(label = "…")]` and value from the field's `InfoValue`.
//! - [`render_info_section`] is the shared driver that replaces every
//!   hand-written `render_section` for flat sections.

use crate::theme::PeekTheme;

use super::{push_field, push_section_header};

/// Render one info-field value to a themed (SGR-painted) string.
///
/// The blanket impls here cover plain field types; [`Value`](super::Value)
/// carries the semantic kinds with bespoke colouring; per-type enums whose
/// human label differs from their serde token impl this directly.
pub trait InfoValue {
    /// Themed value string for the field's `(label, value)` row.
    fn render_value(&self, theme: &PeekTheme) -> String;
}

/// A flat info section: a title and a list of `(label, painted_value)` rows.
/// Generated by `#[derive(InfoSection)]`; consumed by [`render_info_section`].
pub trait InfoSection {
    /// Section header title (the `── Title ──` rule line).
    fn title(&self) -> &'static str;
    /// The rows, in field declaration order, skips already applied.
    fn rows(&self, theme: &PeekTheme) -> Vec<(&'static str, String)>;
}

/// Shared driver: blank spacer, section header, then each row via
/// [`push_field`]. Replaces the hand-written `render_section` for every flat
/// section that derives [`InfoSection`].
pub fn render_info_section<S: InfoSection>(
    lines: &mut Vec<String>,
    section: &S,
    theme: &PeekTheme,
) {
    lines.push(String::new());
    push_section_header(lines, section.title(), theme);
    for (label, value) in section.rows(theme) {
        push_field(lines, label, &value, theme);
    }
}

// --- std blanket impls -----------------------------------------------------
//
// A view struct mixing `Value` fields with plain ones just works. Strings and
// bools paint in the value color; integers reuse the count gradient (the
// common case — a bare integer field is a cardinal). `Option` renders its
// inner value (the empty case is handled by skip, not here); `Vec` joins with
// commas.

impl InfoValue for String {
    fn render_value(&self, theme: &PeekTheme) -> String {
        theme.paint_value(self)
    }
}

impl InfoValue for &str {
    fn render_value(&self, theme: &PeekTheme) -> String {
        theme.paint_value(self)
    }
}

impl InfoValue for bool {
    fn render_value(&self, theme: &PeekTheme) -> String {
        theme.paint_value(if *self { "yes" } else { "no" })
    }
}

macro_rules! impl_info_value_int {
    ($($t:ty),*) => {$(
        impl InfoValue for $t {
            fn render_value(&self, theme: &PeekTheme) -> String {
                super::paint_count(*self as usize, theme)
            }
        }
    )*};
}
impl_info_value_int!(u8, u16, u32, u64, usize, i8, i16, i32, i64, isize);

impl<T: InfoValue> InfoValue for Option<T> {
    fn render_value(&self, theme: &PeekTheme) -> String {
        match self {
            Some(v) => v.render_value(theme),
            None => String::new(),
        }
    }
}

impl<T: InfoValue> InfoValue for Vec<T> {
    fn render_value(&self, theme: &PeekTheme) -> String {
        self.iter()
            .map(|v| v.render_value(theme))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

/// Zero-test backing the derive's print-only `#[info(skip_if_zero)]`. Lets a
/// numeric field — whether a plain integer or a [`Value`](super::Value) of a
/// numeric kind — be hidden from the printed section while JSON still emits
/// its `0`. Non-numeric values are never "zero".
pub trait MaybeZero {
    fn is_zero_value(&self) -> bool;
}

macro_rules! impl_maybe_zero_int {
    ($($t:ty),*) => {$(
        impl MaybeZero for $t {
            fn is_zero_value(&self) -> bool { *self == 0 }
        }
    )*};
}
impl_maybe_zero_int!(u8, u16, u32, u64, usize, i8, i16, i32, i64, isize);

impl MaybeZero for super::Value {
    fn is_zero_value(&self) -> bool {
        use super::Value;
        match self {
            Value::Size(n) | Value::Count(n) | Value::DurationMs(n) => *n == 0,
            Value::Int(n) => *n == 0,
            Value::Ratio(r) => *r == 0.0,
            _ => false,
        }
    }
}
