//! The print half of the info model: [`InfoValue`] (per-field human render)
//! and [`InfoView`] (a whole type's section tree). A view struct that derives
//! both `serde::Serialize` and [`InfoView`](macro@crate::InfoView) drives the
//! two info outputs — machine JSON and themed terminal text — from one place.
//!
//! - [`InfoValue::render_value`] returns a *painted* SGR string for one field,
//!   matching [`push_field`](super::push_field)'s `(label, colored_value)`
//!   contract. The semantic [`Value`](super::Value) enum impls it (size /
//!   count / timestamp gradients live in `render/`); the std blanket impls
//!   below cover plain fields; per-type enums whose print label diverges from
//!   their JSON token impl it themselves (orphan-legal: local type, this
//!   trait).
//! - [`InfoView`] is what `#[derive(InfoView)]` generates: `info_nodes()`
//!   walks the fields in declaration order, producing a tree of [`InfoNode`]s
//!   — scalar fields become [`InfoNode::Row`]s, `#[info(nest)]` fields splice
//!   in a sub-view's nodes (a *titled* sub-view becomes a nested
//!   [`InfoNode::Block`]; an untitled one inlines its rows). Display blocks
//!   and JSON sub-objects are the same structural fact, so the two outputs
//!   stay in step from one definition.
//! - [`render_info`] walks that tree into themed terminal lines, the shared
//!   driver that replaces every hand-written `render_section`.

use std::borrow::Cow;

use crate::theme::PeekTheme;

use super::{push_field, push_section_header};

/// Render one info-field value to a themed (SGR-painted) string.
///
/// The blanket impls here cover plain field types; [`Value`](super::Value)
/// carries the semantic kinds with bespoke colouring; per-type enums whose
/// human label differs from their serde token impl this directly.
pub trait InfoValue {
    /// Themed value string for the field's `(label, value)` row.
    fn render_value(&self, theme: &PeekTheme) -> String;
}

/// One node of an info view: either a labelled value row or a titled block
/// holding further nodes. The tree mirrors the JSON structure — a [`Block`]
/// is a nested object, a [`Row`] a leaf.
///
/// [`Block`]: InfoNode::Block
/// [`Row`]: InfoNode::Row
pub enum InfoNode {
    /// A `Label  value` line. The label is usually a `&'static str` literal
    /// (`"Lines"`), but `Cow` lets a hand-built view supply an owned, dynamic
    /// label (e.g. a CSV column's `" 1: header"`).
    Row {
        label: Cow<'static, str>,
        value: String,
    },
    /// A `── Title ──` section header followed by its body nodes.
    Block { title: String, body: Vec<InfoNode> },
}

impl InfoNode {
    /// Whether this node produces any visible output. A [`Block`](InfoNode::Block)
    /// with no rendering descendants is empty and is skipped entirely (header
    /// included) — the all-optional-absent section vanishes.
    fn renders(&self) -> bool {
        match self {
            InfoNode::Row { .. } => true,
            InfoNode::Block { body, .. } => body.iter().any(InfoNode::renders),
        }
    }
}

/// A type's whole info view: the ordered section/row tree. Generated by
/// `#[derive(InfoView)]`; consumed by [`render_info`] (print) while
/// `serde::Serialize` drives the parallel JSON.
pub trait InfoView {
    /// The view's nodes, in declaration order, skips already applied.
    fn info_nodes(&self, theme: &PeekTheme) -> Vec<InfoNode>;
}

/// A `None` sub-view contributes nothing; `Some` splices its nodes. Lets a
/// `#[info(nest)]` field be `Option<T>` (absent → no block / no rows) without
/// a separate skip attribute.
impl<T: InfoView> InfoView for Option<T> {
    fn info_nodes(&self, theme: &PeekTheme) -> Vec<InfoNode> {
        match self {
            Some(v) => v.info_nodes(theme),
            None => Vec::new(),
        }
    }
}

/// Walk a view's node tree into themed terminal lines — the shared driver
/// that replaces every hand-written `render_section`.
pub fn render_info(lines: &mut Vec<String>, view: &impl InfoView, theme: &PeekTheme) {
    for node in view.info_nodes(theme) {
        render_node(lines, &node, theme);
    }
}

fn render_node(lines: &mut Vec<String>, node: &InfoNode, theme: &PeekTheme) {
    match node {
        InfoNode::Row { label, value } => push_field(lines, label, value, theme),
        InfoNode::Block { title, body } => {
            if !body.iter().any(InfoNode::renders) {
                return;
            }
            lines.push(String::new());
            push_section_header(lines, title, theme);
            for child in body {
                render_node(lines, child, theme);
            }
        }
    }
}

// --- std blanket impls -----------------------------------------------------
//
// A view struct mixing `Value` fields with plain ones just works. Strings and
// bools paint in the value color; integers reuse the count gradient (the
// common case — a bare integer field is a cardinal). `Option` renders its
// inner value (the empty case is handled by skip, not here); `Vec` joins with
// commas.

impl InfoValue for String {
    fn render_value(&self, theme: &PeekTheme) -> String {
        theme.paint_value(self)
    }
}

impl InfoValue for &str {
    fn render_value(&self, theme: &PeekTheme) -> String {
        theme.paint_value(self)
    }
}

impl InfoValue for bool {
    fn render_value(&self, theme: &PeekTheme) -> String {
        theme.paint_value(if *self { "yes" } else { "no" })
    }
}

macro_rules! impl_info_value_int {
    ($($t:ty),*) => {$(
        impl InfoValue for $t {
            fn render_value(&self, theme: &PeekTheme) -> String {
                super::paint_count(*self as usize, theme)
            }
        }
    )*};
}
impl_info_value_int!(u8, u16, u32, u64, usize, i8, i16, i32, i64, isize);

impl<T: InfoValue> InfoValue for Option<T> {
    fn render_value(&self, theme: &PeekTheme) -> String {
        match self {
            Some(v) => v.render_value(theme),
            None => String::new(),
        }
    }
}

impl<T: InfoValue> InfoValue for Vec<T> {
    fn render_value(&self, theme: &PeekTheme) -> String {
        self.iter()
            .map(|v| v.render_value(theme))
            .collect::<Vec<_>>()
            .join(", ")
    }
}

/// Zero-test backing the derive's print-only `#[info(skip_if_zero)]`. Lets a
/// numeric field — whether a plain integer or a [`Value`](super::Value) of a
/// numeric kind — be hidden from the printed section while JSON still emits
/// its `0`. Non-numeric values are never "zero".
pub trait MaybeZero {
    fn is_zero_value(&self) -> bool;
}

macro_rules! impl_maybe_zero_int {
    ($($t:ty),*) => {$(
        impl MaybeZero for $t {
            fn is_zero_value(&self) -> bool { *self == 0 }
        }
    )*};
}
impl_maybe_zero_int!(u8, u16, u32, u64, usize, i8, i16, i32, i64, isize);

impl MaybeZero for super::Value {
    fn is_zero_value(&self) -> bool {
        use super::Value;
        match self {
            Value::Size(n) | Value::Count(n) | Value::DurationMs(n) => *n == 0,
            Value::Int(n) => *n == 0,
            Value::Ratio(r) => *r == 0.0,
            _ => false,
        }
    }
}
