//! Glyph bitmap generator for peek's image renderer.
//!
//! Rasterizes characters from a monospace font at 8x16 resolution and outputs
//! Rust source code defining the glyph atlas.
//!
//! Usage:
//!   cargo run --example gen_glyphs > src/viewer/image/glyph_atlas_data.rs
//!
//! By default, looks for a system monospace font. Override with:
//!   PEEK_FONT=/path/to/font.ttf cargo run --example gen_glyphs

use std::collections::BTreeMap;

use fontdue::{Font, FontSettings};

const CELL_W: usize = 8;
const CELL_H: usize = 16;

/// Line segment characters for "geo" mode — purely geometric, no text noise.
const GEO_CHARS: &str = r"/\|-_";

/// Characters to categorize as "Curated" — distinct spatial patterns useful
/// for image rendering without looking like text.
const CURATED_CHARS: &str = r#"()[]{}<>^.:;,'"!?#@%&*+=~"#;

fn main() {
    let font_path = std::env::var("PEEK_FONT").unwrap_or_else(|_| find_system_font());

    eprintln!("Loading font: {font_path}");
    let font_data = std::fs::read(&font_path).unwrap_or_else(|e| {
        eprintln!("Failed to read font file: {e}");
        eprintln!("Set PEEK_FONT=/path/to/monospace/font.ttf");
        std::process::exit(1);
    });

    let font = Font::from_bytes(font_data, FontSettings::default()).unwrap_or_else(|e| {
        eprintln!("Failed to parse font: {e}");
        std::process::exit(1);
    });

    // Use a larger render size for better quality, then downsample to 8x16.
    // We render at a size where the line height fills our canvas, then place
    // each glyph using its metrics.
    let render_size = find_render_size(&font);
    eprintln!("Using render size: {render_size:.1}px");

    // Get font metrics for cell layout
    let line_metrics = font
        .horizontal_line_metrics(render_size)
        .expect("font must have horizontal metrics");
    let ascent = line_metrics.ascent;
    let cell_advance = {
        // Use 'M' to determine monospace cell width
        let (m_metrics, _) = font.rasterize('M', render_size);
        m_metrics.advance_width
    };

    // The canvas size in font pixels (before downsampling to 8x16)
    let canvas_w = cell_advance.ceil() as usize;
    let canvas_h = (line_metrics.ascent - line_metrics.descent).ceil() as usize;
    eprintln!("Canvas size: {canvas_w}x{canvas_h} (ascent={ascent:.1})");

    // Collect all character ranges to rasterize
    let mut chars_to_render: Vec<(char, &str)> = Vec::new();

    // Printable ASCII (32–126)
    for cp in 32u32..=126 {
        if let Some(ch) = char::from_u32(cp) {
            let cat = if GEO_CHARS.contains(ch) {
                "Geo"
            } else if CURATED_CHARS.contains(ch) {
                "Curated"
            } else {
                "Extended"
            };
            chars_to_render.push((ch, cat));
        }
    }

    // Latin-1 Supplement (160–255)
    for cp in 160u32..=255 {
        if let Some(ch) = char::from_u32(cp) {
            chars_to_render.push((ch, "Extended"));
        }
    }

    // Box-drawing characters (U+2500–U+257F)
    for cp in 0x2500u32..=0x257F {
        if let Some(ch) = char::from_u32(cp) {
            chars_to_render.push((ch, "Extended"));
        }
    }

    // Geometric shapes (U+25A0–U+25FF)
    for cp in 0x25A0u32..=0x25FF {
        if let Some(ch) = char::from_u32(cp) {
            chars_to_render.push((ch, "Extended"));
        }
    }

    // Rasterize and collect results
    let mut glyphs: BTreeMap<char, (u128, &str)> = BTreeMap::new();
    let mut skipped = 0;

    for (ch, category) in &chars_to_render {
        // Skip space — it's handled as a block element in the atlas
        if *ch == ' ' {
            continue;
        }

        let glyph_index = font.lookup_glyph_index(*ch);
        if glyph_index == 0 {
            skipped += 1;
            continue;
        }

        let (metrics, bitmap) = font.rasterize(*ch, render_size);

        if metrics.width == 0 || metrics.height == 0 {
            skipped += 1;
            continue;
        }

        // Compose glyph onto a full-cell canvas using metrics
        let canvas = compose_glyph_on_canvas(
            &bitmap,
            &metrics,
            canvas_w,
            canvas_h,
            ascent,
        );

        // Downsample canvas to 8x16 binary bitmap
        let bits = downsample_to_bitmap(&canvas, canvas_w, canvas_h);

        // Skip empty bitmaps (would just be a space) and full bitmaps (would be full block)
        let popcount = bits.count_ones();
        if popcount == 0 || popcount == 128 {
            skipped += 1;
            continue;
        }

        glyphs.insert(*ch, (bits, category));
    }

    eprintln!(
        "Generated {} glyphs, skipped {} (missing/empty/trivial)",
        glyphs.len(),
        skipped
    );

    // Output Rust source
    println!("// Generated by: cargo run --example gen_glyphs");
    println!("// Font: {font_path}");
    println!("// Do not edit manually — regenerate with the gen_glyphs tool.");
    println!();
    println!("static GENERATED_GLYPHS: &[GlyphBitmap] = &[");

    for (ch, (bits, category)) in &glyphs {
        let ch_escaped = escape_char(*ch);
        println!(
            "    GlyphBitmap {{ ch: {ch_escaped}, bits: 0x{bits:032X}, category: GlyphCategory::{category} }},"
        );
    }

    println!("];");
}

/// Compose a rasterized glyph onto a cell-sized canvas using font metrics.
///
/// The canvas represents the full character cell. The glyph bitmap from fontdue
/// is just the bounding box of the ink; we need to place it at the correct
/// position within the cell using xmin and ymin offsets relative to the baseline.
fn compose_glyph_on_canvas(
    bitmap: &[u8],
    metrics: &fontdue::Metrics,
    canvas_w: usize,
    canvas_h: usize,
    ascent: f32,
) -> Vec<u8> {
    let mut canvas = vec![0u8; canvas_w * canvas_h];

    // fontdue metrics:
    // - xmin: horizontal offset from the origin to the left edge of the glyph bbox
    // - ymin: vertical offset from the origin (baseline) to the bottom edge of the glyph bbox
    //   (positive = above baseline in fontdue's convention)
    //
    // In our canvas coordinate system (0,0 = top-left, y increases downward):
    // - baseline is at y = ascent (from top)
    // - glyph top edge = ascent - (ymin + height)
    // - glyph left edge = xmin

    let glyph_top = ascent as i32 - metrics.ymin - metrics.height as i32;
    let glyph_left = metrics.xmin;

    for gy in 0..metrics.height {
        for gx in 0..metrics.width {
            let canvas_x = glyph_left + gx as i32;
            let canvas_y = glyph_top + gy as i32;

            if canvas_x >= 0
                && canvas_x < canvas_w as i32
                && canvas_y >= 0
                && canvas_y < canvas_h as i32
            {
                let src_idx = gy * metrics.width + gx;
                let dst_idx = canvas_y as usize * canvas_w + canvas_x as usize;
                canvas[dst_idx] = bitmap[src_idx];
            }
        }
    }

    canvas
}

/// Downsample a canvas (arbitrary size) to an 8x16 binary bitmap packed as u128.
///
/// Uses area sampling: for each 8x16 output cell, averages the corresponding
/// region of the canvas and thresholds at 128.
fn downsample_to_bitmap(canvas: &[u8], canvas_w: usize, canvas_h: usize) -> u128 {
    let mut bits: u128 = 0;

    for row in 0..CELL_H {
        for col in 0..CELL_W {
            // Map this output pixel to a region in the canvas
            let src_y0 = row * canvas_h / CELL_H;
            let src_y1 = ((row + 1) * canvas_h / CELL_H).max(src_y0 + 1);
            let src_x0 = col * canvas_w / CELL_W;
            let src_x1 = ((col + 1) * canvas_w / CELL_W).max(src_x0 + 1);

            // Average the pixel values in this region
            let mut sum = 0u32;
            let mut count = 0u32;
            for sy in src_y0..src_y1.min(canvas_h) {
                for sx in src_x0..src_x1.min(canvas_w) {
                    sum += canvas[sy * canvas_w + sx] as u32;
                    count += 1;
                }
            }

            let avg = if count > 0 { sum / count } else { 0 };

            // Threshold: > 128 means "ink"
            if avg > 128 {
                bits |= 1u128 << (row * CELL_W + col);
            }
        }
    }

    bits
}

/// Find a render size where the font's line height is large enough for
/// good-quality downsampling. We want at least 32px tall for the cell
/// (2x our target of 16), but more is better up to a point.
fn find_render_size(font: &Font) -> f32 {
    // Target: canvas height of ~48px (3x our 16px target) for good sampling
    let target_canvas_h: f32 = 48.0;

    for trial in [24.0f32, 32.0, 40.0, 48.0, 56.0, 64.0] {
        if let Some(lm) = font.horizontal_line_metrics(trial) {
            let line_h = lm.ascent - lm.descent;
            if line_h >= target_canvas_h {
                return trial;
            }
        }
    }

    // Fallback: scale based on what we can get
    if let Some(lm) = font.horizontal_line_metrics(32.0) {
        let line_h = lm.ascent - lm.descent;
        if line_h > 0.0 {
            return 32.0 * target_canvas_h / line_h;
        }
    }

    32.0 // absolute fallback
}

/// Escape a char for Rust source output.
fn escape_char(ch: char) -> String {
    match ch {
        '\'' => "'\\''".to_string(),
        '\\' => "'\\\\'".to_string(),
        c if c.is_ascii_graphic() || c == ' ' => format!("'{c}'"),
        c => format!("'\\u{{{:04X}}}'", c as u32),
    }
}

/// Try to find a system monospace font.
fn find_system_font() -> String {
    let candidates = [
        // macOS
        "/System/Library/Fonts/Menlo.ttc",
        "/System/Library/Fonts/Monaco.ttf",
        "/System/Library/Fonts/Courier.ttc",
        "/System/Library/Fonts/SFNSMono.ttf",
        // Linux common locations
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/TTF/DejaVuSansMono.ttf",
        "/usr/share/fonts/dejavu-sans-mono-fonts/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
        "/usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf",
    ];

    for path in candidates {
        if std::path::Path::new(path).exists() {
            return path.to_string();
        }
    }

    eprintln!("No system monospace font found. Set PEEK_FONT=/path/to/font.ttf");
    std::process::exit(1);
}
